In [6]:
!pip install numpy
import numpy as np

In [7]:
nums_array = np.array([1, 2, 3, 4, 5])
nums_array

array([1, 2, 3, 4, 5])

In [ ]:
type(nums_array)

numpy.ndarray

In [8]:
nums_array[-1]

np.int64(5)

In [9]:
nums_array.shape

(5,)

In [10]:
nums_array.ndim

1

In [12]:
nums_array.itemsize

8

In [11]:
nums_array.size

5

In [14]:
nums_array.dtype

dtype('int64')

In [15]:
some_array = np.array([True, 'banana', 777])
some_array

array(['True', 'banana', '777'], dtype='<U21')

In [16]:
some_array.dtype

dtype('<U21')

## Dimensional Arrays


In [25]:
first_array = np.array([[43, 32, 323], [44, 35, 226]])
second_array = np.array([[10, 297, 233], [4, 5784, 4446]])

# print(first_array)
# print(second_array)

In [23]:
first_array.shape

(2, 3)

In [27]:
first_array[1, 0]

np.int64(44)

### Arithmetic operations with numpy arrays


In [28]:
# +
first_array + second_array

array([[  53,  329,  556],
       [  48, 5819, 4672]])

In [29]:
# + 1
first_array + 1

array([[ 44,  33, 324],
       [ 45,  36, 227]])

In [30]:
# /
first_array / second_array

array([[4.30000000e+00, 1.07744108e-01, 1.38626609e+00],
       [1.10000000e+01, 6.05117566e-03, 5.08322087e-02]])

In [31]:
# -
first_array - 1

array([[ 42,  31, 322],
       [ 43,  34, 225]])

In [32]:
# -
first_array - second_array

array([[   33,  -265,    90],
       [   40, -5749, -4220]])

In [33]:
# *
first_array * second_array

array([[    430,    9504,   75259],
       [    176,  202440, 1004796]])

###  Concatenating NumPy Arrays



In [34]:
np.concatenate((first_array, second_array))

array([[  43,   32,  323],
       [  44,   35,  226],
       [  10,  297,  233],
       [   4, 5784, 4446]])

In [36]:
np.concatenate((np.array([4, 5, 6]), np.array([7, 8, 9])))

array([4, 5, 6, 7, 8, 9])

In [37]:
np.concatenate((first_array, second_array), axis=1)

array([[  43,   32,  323,   10,  297,  233],
       [  44,   35,  226,    4, 5784, 4446]])