## Example 1. Calculating Total Revenue


In [2]:

!pip install numpy
import numpy as np

In [3]:
prices = np.array([20.99, 21, 99, 58.99, 15.99, 85.99])
prices

array([20.99, 21.  , 99.  , 58.99, 15.99, 85.99])

In [4]:
quantities = np.array([15, 17, 20, 8, 7, 1])
quantities

array([15, 17, 20,  8,  7,  1])

In [5]:
prices_with_quantities = prices * quantities
prices_with_quantities

array([ 314.85,  357.  , 1980.  ,  471.92,  111.93,   85.99])

In [6]:
total_revenue = np.sum(prices_with_quantities)
total_revenue

np.float64(3321.6899999999996)

## Example 2. Analyzing Blog Post Stats

In [7]:
views = np.array([800, 1000, 850, 900, 700, 2000])
views

array([ 800, 1000,  850,  900,  700, 2000])

In [8]:
max_views = np.max(views)
max_views

np.int64(2000)

In [9]:
min_views = np.min(views)
min_views

np.int64(700)

In [10]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(1041.67)

In [11]:
total_views = np.sum(views)
total_views

np.int64(6250)

## Example 3. Splitting Order Into Batches


In [12]:
order_ids = np.array([5555, 6666, 7777, 9999, 3333, 2222])
order_ids

array([5555, 6666, 7777, 9999, 3333, 2222])

In [13]:
batches = np.split(order_ids, 3)
batches

[array([5555, 6666]), array([7777, 9999]), array([3333, 2222])]

In [14]:
for batche in batches:
    print(batche)

[5555 6666]
[7777 9999]
[3333 2222]


## Example 4. Categorizing Product Rating

In [15]:
ratings = np.array([4.5, 5.0, 3.0, 4.5, 3.7, 4.8])
ratings

array([4.5, 5. , 3. , 4.5, 3.7, 4.8])

In [16]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.5, 4.8])

In [17]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3. , 3.7])

## Example 5. Calculating Total and Average quantities sold


In [18]:
# each column is specific product in the order
# each row represents specific order
order_quantities = np.array([[12, 5, 4, 1, 5], [8, 8, 15, 12, 3]])
order_quantities

array([[12,  5,  4,  1,  5],
       [ 8,  8, 15, 12,  3]])

In [19]:
total_order_quantities = np.sum(order_quantities)
total_order_quantities

np.int64(73)

In [20]:
# quantities of the sales in each product
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([20, 13, 19, 13,  8])

In [21]:
# quantities of the sales in each order
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([27, 46])

In [22]:
# average quantities per product
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([10. ,  6.5,  9.5,  6.5,  4. ])

## Example 6. Calculating Average product Rating and Maximum rating per Category

In [23]:
# each row represents specific product
# each product is rated in  different categories
product_reviews = np.array(
    [[4.5, 5.0, 3.0, 4.5, 3.7, 4.8], [1.5, 4.0, 5.0, 4.5, 3.7, 4.8], [2.5, 3.5, 5.0, 5.0, 4.7, 4.9]])
product_reviews

array([[4.5, 5. , 3. , 4.5, 3.7, 4.8],
       [1.5, 4. , 5. , 4.5, 3.7, 4.8],
       [2.5, 3.5, 5. , 5. , 4.7, 4.9]])

In [24]:
average_rating = np.mean(product_reviews, axis=1)
average_rating

array([4.25      , 3.91666667, 4.26666667])

In [25]:
max_rating_per_category = np.max(product_reviews, axis=0)
max_rating_per_category

array([4.5, 5. , 5. , 5. , 4.7, 4.9])

## Example 7. Generation of the sample stock data

In [26]:
companies = ['google', 'amazon', 'apple']
days = ['Monday, 2 January', 'Tuesday, 2 February']
price_types = ['open', 'close', 'high', 'low']

In [27]:
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [28]:
stock_prices.shape

(3, 2, 4)

In [29]:
for index_axis_0, company in enumerate(companies):
    print(f'stock prices for the {company}:')
    for index_axis_1, day in enumerate(days):
        print(f'day: {day}')
        for index_axis_2, price_type in enumerate(price_types):
            print(f'{price_type} price: {stock_prices[index_axis_0, index_axis_1, index_axis_2 ]}')
        print('')
    print('')

stock prices for the google:
day: Monday, 2 January
open price: 0.417
close price: 0.72
high price: 0.0
low price: 0.302

day: Tuesday, 2 February
open price: 0.147
close price: 0.092
high price: 0.186
low price: 0.346


stock prices for the amazon:
day: Monday, 2 January
open price: 0.397
close price: 0.539
high price: 0.419
low price: 0.685

day: Tuesday, 2 February
open price: 0.204
close price: 0.878
high price: 0.027
low price: 0.67


stock prices for the apple:
day: Monday, 2 January
open price: 0.417
close price: 0.559
high price: 0.14
low price: 0.198

day: Tuesday, 2 February
open price: 0.801
close price: 0.968
high price: 0.313
low price: 0.692


