# Random values

## Specify specific values

In [79]:
import numpy as np
from numpy.ma.core import negative

In [80]:
#.zeros()
zeros_example = np.zeros((3, 5))
zeros_example

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
#.ones()
ones_example = np.ones((2, 4))
ones_example

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Specify random values

In [82]:
#.random.random
random_random_example = np.random.random((5, 5))
random_random_example

array([[0.98464131, 0.86980588, 0.2140398 , 0.65005787, 0.84038379],
       [0.84573448, 0.70768596, 0.63820231, 0.69977778, 0.24902856],
       [0.44551339, 0.8006973 , 0.69380854, 0.1450738 , 0.57183033],
       [0.70629307, 0.87898522, 0.73285338, 0.59733697, 0.85067621],
       [0.05988868, 0.58902981, 0.56275623, 0.49330573, 0.86310201]])

In [83]:
#.random.randint
random_randint_example = np.random.randint(2, 10, size=(2, 5))
random_randint_example

array([[2, 4, 7, 4, 6],
       [3, 3, 3, 3, 7]])

In [84]:
#.random.uniform 1 2 dem array
random_uniform_example = np.random.uniform(5, 15, size=(3, 7))
random_uniform_example

array([[13.40318587,  8.17473109,  9.89396571,  9.31078979, 12.88110576,
         7.66685578,  7.38564755],
       [ 5.52640218, 13.42835263, 14.88748028,  7.97769908, 11.18863893,
         8.95688345, 11.32615457],
       [ 6.19558589,  6.61941627,  7.73792596,  5.35675235,  5.63087409,
        12.17556013, 12.24099068]])

In [85]:
#.random.seed
np.random.seed(10)
random_seed_example = np.random.uniform(5, 15, size=(3, 7))
random_seed_example

array([[12.71320643,  5.20751949, 11.33648235, 12.48803883,  9.98507012,
         7.24796646,  6.98062865],
       [12.60530712,  6.69110837,  5.88339814, 11.85359818, 14.53393346,
         5.03948266, 10.12192263],
       [13.12620962, 11.12526067, 12.21755317,  7.91876068, 14.17774123,
        12.14575783, 10.42544368]])

In [86]:
#.random.seed proof, if we have the same value in the seed()
np.random.seed(10)
random_seed_example2 = np.random.uniform(5, 15, size=(3, 7))
random_seed_example2

array([[12.71320643,  5.20751949, 11.33648235, 12.48803883,  9.98507012,
         7.24796646,  6.98062865],
       [12.60530712,  6.69110837,  5.88339814, 11.85359818, 14.53393346,
         5.03948266, 10.12192263],
       [13.12620962, 11.12526067, 12.21755317,  7.91876068, 14.17774123,
        12.14575783, 10.42544368]])

In [87]:
#.random.seed
np.random.seed(9)
random_seed_example3 = np.random.uniform(5, 15, size=(3, 7))
random_seed_example3

array([[ 5.10374154, 10.01874592,  9.95773293,  6.33829529,  6.42111085,
         7.18558676,  9.18508181],
       [ 7.48101168,  5.84059651,  8.4549864 ,  6.66776347, 13.78559086,
        14.50964032,  5.38748376],
       [11.99107391, 10.72759816, 13.98007118, 11.66898973, 10.47837783,
        12.02427424,  8.8647717 ]])

# arrange/ reshape/ flatten


In [88]:
#.arange
arange_example1 = np.arange(5)
arange_example1

array([0, 1, 2, 3, 4])

In [89]:
arange_example2 = np.arange(5, 10)
arange_example2

array([5, 6, 7, 8, 9])

In [90]:
arange_example3 = np.arange(7, 21, 3)
arange_example3

array([ 7, 10, 13, 16, 19])

In [98]:
negative_arange = np.arange(-5, 14, 2)
negative_arange

array([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13])

In [91]:
#.reshape
np.arange(30).reshape([3, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [92]:
np.array([2, 1, 545, 64, 153, 1]).reshape([2, 3])

array([[  2,   1, 545],
       [ 64, 153,   1]])

In [108]:
np.random.seed(2)
reshape_reshape_example = np.random.random([4, 4, 3]).reshape([2,24]).reshape([48, 1])
print(reshape_reshape_example)

[[0.4359949 ]
 [0.02592623]
 [0.54966248]
 [0.43532239]
 [0.4203678 ]
 [0.33033482]
 [0.20464863]
 [0.61927097]
 [0.29965467]
 [0.26682728]
 [0.62113383]
 [0.52914209]
 [0.13457995]
 [0.51357812]
 [0.18443987]
 [0.78533515]
 [0.85397529]
 [0.49423684]
 [0.84656149]
 [0.07964548]
 [0.50524609]
 [0.0652865 ]
 [0.42812233]
 [0.09653092]
 [0.12715997]
 [0.59674531]
 [0.226012  ]
 [0.10694568]
 [0.22030621]
 [0.34982629]
 [0.46778748]
 [0.20174323]
 [0.64040673]
 [0.48306984]
 [0.50523672]
 [0.38689265]
 [0.79363745]
 [0.58000418]
 [0.1622986 ]
 [0.70075235]
 [0.96455108]
 [0.50000836]
 [0.88952006]
 [0.34161365]
 [0.56714413]
 [0.42754596]
 [0.43674726]
 [0.77655918]]


In [93]:
check_type = np.arange(20)
type(check_type)

numpy.ndarray

In [95]:
np.arange(60).reshape([5, 3, 4])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [94]:
#.flatten
three_dimension_array = np.random.random((2, 5, 10))
single_dimension_array = np.round(three_dimension_array.flatten(), 2)
single_dimension_array

array([0.69, 0.82, 0.47, 0.94, 0.8 , 0.98, 0.17, 0.52, 0.95, 0.65, 0.86,
       0.97, 0.19, 0.24, 0.87, 0.91, 0.76, 0.35, 0.46, 0.61, 0.5 , 0.48,
       0.44, 0.87, 0.19, 0.69, 0.7 , 0.93, 0.04, 0.65, 0.64, 0.46, 0.05,
       0.04, 0.17, 0.79, 0.16, 0.14, 0.35, 0.48, 0.7 , 0.8 , 0.27, 0.91,
       0.02, 0.38, 0.2 , 0.34, 0.44, 0.5 , 0.41, 0.21, 0.22, 0.23, 0.73,
       0.42, 0.58, 0.49, 0.43, 0.73, 0.56, 0.3 , 0.97, 0.22, 0.14, 0.61,
       0.49, 0.18, 0.11, 0.54, 0.29, 0.1 , 0.49, 0.63, 0.04, 0.5 , 0.08,
       0.79, 0.76, 0.26, 0.1 , 0.92, 0.52, 0.13, 0.11, 0.84, 0.55, 0.26,
       0.58, 0.31, 0.79, 0.49, 0.97, 0.52, 0.9 , 0.25, 0.52, 0.51, 0.81,
       0.07])